@DemoFluentValidationPlusActionFilterPlusActionFilter_HostAddress = http://localhost:5106

GET {{DemoFluentValidationPlusActionFilterPlusActionFilter_HostAddress}}/weatherforecast/
Accept: application/json

###
